GET http://localhost:5000/api/v1/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJhZG1pbiIsImdlbmRlciI6Im1hbGUiLCJpYXQiOjE2OTYzMjYyOTcsImV4cCI6MTY5NjMyNjM0N30.QqvT0BbJ5hxuQAzazxDoPwFKhaTg56zHBbnEGPzilC8

###
POST http://localhost:5000/api/v1/users/
Content-Type: application/json

{
    "name": "publik1",
    "email": "publik1@admin.com",
    "password": "publik1",
    "confirmPassword": "publik1",
    "gender": "female"
}

###
POST http://localhost:5000/api/v1/login/
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
GET  http://localhost:5000/api/v1/token

###
DELETE http://localhost:5000/api/v1/logout

