
POST http://localhost:5000/api/v1/condition/
Content-Type: application/json

{
    "name": "distanceVisionExamination",
    "lowerLimit": "20/20",
    "upperLimit": "20/90",
    "satuan": "meter",
    "status": "Normal",
    "saran": "Konsul Ke Dokter Spesialis Mata"
}



### Get all condition
GET http://localhost:5000/api/v1/condition/
Content-Type: application/json

{
  
}

