// Untuk Mengambil Antrian
POST            
Content-Type: application/json

{
    
}
###
// Antrian Saat ini
GET http://localhost:5000/api/v1/queue/
Content-Type: application/json

{
 
}

###
// Reset Antrian
DELETE  http://localhost:5000/api/v1/queue/
Content-Type: application/json

{

}

###
